### ISSUE TITLE
Java 9+ Compatibility

### ISSUE THREAD

**Issue by MikeDombo** [awslabs/aws-crt-java#311] opened 2021-04-24 07:22 UTC
https://github.com/awslabs/aws-crt-java/blob/652a6f853a35cd064dbe1dbff4aedee197991b37/src/native/java_class_ids.c#L204,L210

The ByteBuffer methods won't be able to be found on Java 9+ due to Java's changing the return type to be `ByteBuffer` instead of the superclass `Buffer`

You may need to update the code to look for what it looks for now, and then if that fails try to look for the other version.

**Comment by bretambrose** [comment] 2021-05-18 21:48
I'm running the samples without issue with jdk11 targeting jre11.  Is there something additional that needs to be done to surface this?  It appears that Buffer still has the method in question (and is probably the exact same thing really) so is it possible that the jni lookup is actually mapping to the Buffer method and everything still works?

**Comment by MikeDombo** [comment] 2021-05-18 21:51
I hit this issue when building with graal native image for jdk 11.

**Comment by jmklix** [comment] 2024-05-06 23:26
Closing: duplicate of this FR - https://github.com/awslabs/aws-crt-java/issues/780

**Closed by jmklix** 2024-05-06 23:26 UTC
Labels: feature-request, p2
